import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex flex-col min-h-screen">
          <NavBar />
          <div className="flex-auto h-0">{children}</div>
        </div>
      </body>
    </html>
  )
}

function NavBar() {
  return (
    <nav>
      <ul className="flex p-2 gap-2 bg-neutral-400">
        <li>
          <Link href="static-embed">
            <NavButton>Static Embedding</NavButton>
          </Link>
        </li>
        <li>
          <Link href="interactive-embed">
            <NavButton>Interactive Embedding</NavButton>
          </Link>
        </li>
      </ul>
    </nav>
  )
}

function NavButton({ children }) {
  return <button className="px-5 py-2 bg-neutral-300 rounded-xl">{children}</button>
}
